import type { Metadata } from "next";

import "@/styles/index.css";
import { figtree, nunito, urbanist } from "@/libs/font";
import PromoBanner from "@/_components/ui/PromoBanner";
import Navbar from "@/_components/layout/Navbar";
import HeroImage from "./(home)/_components/HeroImage";
import heroImgD from "@/assets/img/hero-image.webp";
import heroImgM from "@/assets/img/hero-image-m.webp";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${urbanist.variable} ${figtree.variable} ${nunito.variable}`}
    >
      <body className={`max-w-[1440px] mx-auto font-figtree`}>
        <PromoBanner />

        <div className="md:px-[13.2rem] space-y-[3.653rem] md:relative flex flex-col ">
          <Navbar />
          <HeroImage
            className="absolute  md:hidden -z-10 top-[7px] left-[50.4%] transform -translate-x-1/2 w-[310px]"
            imgSrc={heroImgM}
          />
          {children}
          <HeroImage
            className="md:absolute md:right-[32px] md:top-[22px] md:-z-10 h-full md:w-[51%]  md:block hidden"
            imgSrc={heroImgD}
          />
        </div>
      </body>
    </html>
  );
}
