import type { Metadata } from "next";

import "@/styles/index.css";
import { figtree, urbanist } from "@/libs/font";
import PromoBanner from "@/_components/ui/PromoBanner";
import Navbar from "@/_components/layout/Navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${urbanist.variable} ${figtree.variable}`}>
			<body className={`max-w-[1440px] mx-auto ${figtree.className} `}>
				<PromoBanner />

				<div className="px-[13.2rem] space-y-[3.653rem]">
					<Navbar />
					{children}
				</div>
			</body>
		</html>
	);
}
